server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a123456
    url: jdbc:mysql://localhost:3306/ds_0?serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:*.xml
  type-aliases-package: com.jh.myspringboot1.modal

