server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a123456
    url: jdbc:mysql://localhost:3306/ds_0?serverTimezone=Asia/Shanghai
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jh.myspringboot1.modal
logging:
  level:
    com:
        jh:
           myspringboot1:
             dao: debug



